components/Account.tsx, package-lock.json, package.json, pages/api/hello.js, pages/api/polygon.js, pages/index.tsx, styles/globals.css, yarn.lock
=> Third dot + tooltips and links

pages/api/polygon.js
Fixes #34 - checking that the transaction's "from" address is equal to the user's wallet address to validate dot 4.
pinging @slavingia for review.
=> fixes issue #34

.gitignore, cache/solidity-files-cache.json, contracts/game.sol, contracts/trophy.sol, hardhat.config.js, package-lock.json, package.json, test/game.js, yarn.lock
=> Game smart contract

pages/api/polygon.ts
=> Remove debugging log

README.md
=> add link to polygonscan apis and use codeblocks for code

pages/index.tsx, styles/globals.css
This should make things a lot easier for us to verify folks so that they can get their tokens!
Old:
New:
=> Game winning 5x more self-serve

pages/index.tsx
- Detect Polygon ChainID in MetaMask
- Use polygon FWEB3 tokens
- third dot
- polygon contract
- notion
- UX improvements
- cp
- 3rd dot working via polygonscan
- cp
- cp
- cp
- fourth dot
- skeleton of sharing code
- cp
- cp
- cp
- trim share
- cp
- cp
- view wallets
- fix for issue #32
- remove console.log
- check that wallet address is sender to complete dot 4
- fixes issue 36 by exiting function before invoking polygonscan api if wallet address is undefined
- cp
- fweb3 diamond nft smart contract
- cp
- cp
- cp
- cp
- cp
- cp
- cp
- cp
- cp
- Add example .env.local file
- Implements #12 Tracks burned tokens
- Filter to the senders address too
- Apply Prettier
- Remove .env.local.example
- Add .env.local.example
- Make first dot pulse if not connected to metamask
- Show the first dot …
=> Add link to PolygonScan from wallet address

pages/api/polygon.ts
Not sure if MintedNFT is not showing for some folks is due to polyscan 5 per-second rate limit. Could not replicate issue locally. 
Please review thanks.
=> Adding 300ms delay per fetch to delay Polyscan Rate Limiting

package-lock.json, package.json, pages/index.tsx, yarn.lock
Refactors the Dots content and UI elements, no changes to behavior nor appearance
1. Extracts Dots content and puts the content into an object
2. Takes Dots HTML and creates a reusable Dots component
I think some of these refactors will actually make some subsequent work faster and less error prone. For example the work in https://github.com/slavingia/fweb3.xyz/pull/77 to get walkthrough content on Dot click (even though there'll be some conflicts)
I intentionally kept this PR as small as possible without changing any behavior or appearance. I (or @slinlee, etc) can then make subsequent PRs like the things in his list https://github.com/slavingia/fweb3.xyz/pull/77#issuecomment-1048541622
The general direction is like 
```js
const dot0Body = <p>things, <img src="" /> and stuff </p>
const …
```
=> Refactor dots content and component

.lintstagedrc.js, components/GameFinish.tsx, package.json, pages/api/polygon.ts, pages/index.tsx, styles/globals.css
1. Lint-staged configuration was present in both package.json and .lintstagedrc.js. I've removed the former.
2. Ran prettier on all code.
=> Fix linting and format all code

components/GameFinish.tsx, components/Trophy.tsx, pages/api/polygon.ts, pages/index.tsx
Trophy image now links to opensea for that trophy.
=> added opensea link

pages/api/polygon.ts
Moved trophy api call up. Still kept it under the balance api call, because we want to show number of tokens.
=> moved trophy api call up

cypress/integration/walkthrough.js, cypress/support/helper.js
- Added test cases for verifying dot color before and after clicking. 
- Also created new helper.js file for common functionality which can be used across the test cases.
=> Added test cases for verifying dot color before and after clicking. 

pages/index.tsx, styles/globals.css
=> Next dot UX

components/ENSLookup.tsx, cypress/integration/ens_lookup.js, hooks/useENSName.ts, pages/index.tsx
Fixed useENSName hook and added ENSLookup component.
=> Ens lookup

pages/index.tsx
Adding some text to remind users that they need to be connected to the Polygon Network.
=> Add reminder to connect to Polygon Network

components/Trophy.tsx, pages/index.tsx, styles/globals.css
- Fixed image size
- Fixed a couple clobbered over styles and weird structures around it.
=> Fix trophy image

.github/workflows/main.yml
- Removes redundant test run when PR are created.
- Resolves #181 - Runs the E2E tests for each PR
=> Run E2E tests on each PR

lib/polygon/validators.ts, pages/index.tsx
Re word the faucet info text to reflect the current faucet amounts
=> Update game text around faucets and fix faucet bug

lib/constants.ts, lib/polygon/api.ts, lib/polygon/endpoints.ts, lib/polygon/validators.ts
Fixed "lights" 3, 4, and 6 by doing the following:
Corrected burn address
Added polygon api to retrieve internal transactions for the wallet
Checked for receiving MATIC from faucet inside the internal transactions
Fixed case sensitivity matching
=> Fixed lights 3,4,6
